version: '3'

networks:
  backend:
    name: app
    driver: bridge


services:

  # Spring Boot App
  app:
    image: "he4rt-start-raw"
    container_name: he4rt-start-raw
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db
      - keycloak

  # Spring Boot Database
  db:
    image: postgres:latest
    container_name: spring-db
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: he4rt-start




  # KeyCloak
  keycloak-db:
    image: postgres
    container_name: keycloak-db
    volumes:
      - ./keycloak-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - backend
    ports:
      - "5433:5432"

  # Auth service
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
#      DB_SCHEMA: public

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8081/admin
    ports:
      - "8081:8080"
    command: start-dev
    networks:
      - backend
    depends_on:
      - keycloak-db